<?php
/**
*
* "PublishDate" module
*
*/
class ProcessWirePublishDate extends WireData implements Module, ConfigurableModule {

    /**
     * getModuleInfo is a module required by all modules to tell ProcessWire about them
     *
     * @return array
     *
     */
    public static function getModuleInfo() {
         return array (
             'title' => 'Set Publish Date',
             'version' => 110,
             'summary' => 'Adds a publish date to every page',
             'singular' => true,
             'autoload' => true
         );
    }

    public function __construct() {
        $this->autoadd_publish_date = false;
    }

    /**
     * Initialize the module
     *
     * ProcessWire calls this when the module is loaded. For 'autoload' modules, this will be called
     * when ProcessWire's API is ready. As a result, this is a good place to attach hooks.
     *
     */
    public function init() {
         // add a hook after the $pages->save
         $this->pages->addHookAfter('save', $this, 'afterSave');
    }

    public function afterSave($event) {
        // get page object saved
        $page = $event->argumentsByName('page');

        if(!$page->template->hasField('publish')) {
            // if option is set, add the publish field
            if ($this->autoadd_publish_date) {
                $field = $this->fields->get('publish');
                // add field if not created already
                if (!$field) {
                    $field = new Field();
                    $field->type = $this->modules->get('FieldtypeDatetime');
                    $field->name = 'publish';
                    $field->collapsed = 4;
                    $field->save();
                }
                $page->template->fields->add($field);
                $page->template->fields->save();
            } else {
                // if publis_date is not present and should not be created automatically
                return;
            }
        }

        if($page->is(Page::statusUnpublished)) {
            // if unpublished, empty the field if not empty already
            if(!$page->publish) return;
            $page->publish = '';
            $page->save('publish');
        } else if(!$page->publish) {
            // if page (published) and field not populated, add current timestamp
            $page->publish = time();
            $page->save('publish');
        }
    }

    /**
     * Configure the module
     *
     */
    public static function getModuleConfigInputfields(array $data) {

        $wrap = new InputfieldWrapper();

        $f = wire('modules')->get('InputfieldCheckbox'); 
        $f->attr('name', 'autoadd_publish_date'); 
        $f->label = __('Add \'publish\' to all pages automatically'); 
        $f->description = __('If you activate this option, ProcessWire will automatically add a \'publish\' field to all templates');
        $f->notes = __('If you leave this option unchecked, you will have to create a \'publish\' field manually and add it to the templates you want it to appear on.'); 
        $f->attr('checked', isset($data['autoadd_publish_date']) ? $data['autoadd_publish_date'] : ''); 
        $wrap->add($f); 

        return $wrap;

    }

}